# Generated by Django 3.1.2 on 2022-04-04 12:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('advertisements', '0002_auto_20220403_1938'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsersFavorite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='advertisements.advertisement')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='advertisement',
            name='users',
            field=models.ManyToManyField(blank=True, null=True, related_name='favorite', through='advertisements.UsersFavorite', to=settings.AUTH_USER_MODEL),
        ),
    ]
